version: '2'
services:

  mongo:
    image: mongo:3.6.3
    ports:
    - 27017:27017
    command: --smallfiles
    volumes:
      - './data:/data/db'


  mongoclient:
    image: mongoclient/mongoclient:latest
    ports:
      - 3000:3000
    links:
      - mongo

  salerev:
    image: ismaelmase/salesrev
    ports:
      - 8080:8080
    links:
      - mongo