version: '3.1'
services:
  salerev:
    image: ismaelmase/salerev
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    ports:
        - 27017:27017

  mongoclient:
    image: mongoclient/mongoclient:latest
    ports:
      - 3000:3000